kind: pipeline
steps:
- name: upload-docker-image
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo:
      from_secret: tx_docker_repo
    registry:
      from_secret: tx_docker_registry
    tags: ${DRONE_TAG=latest}
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: wanglulu.store
    username:
      from_secret: server_username
    password:
      from_secret: server_password
    envs: [USERNAME, PASSWORD, tx_docker_repo, tx_docker_registry]
    port: 22
    script:
      - sudo docker login --username=$USERNAME --password=$PASSWORD $tx_docker_registry
      - sudo docker stop webgl
      - sudo docker rm webgl
      - sudo docker pull $tx_docker_repo:${DRONE_TAG=latest}
      - sudo docker run -d --name webgl -p 3006:80 $tx_docker_repo:${DRONE_TAG=latest}
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
    tx_docker_repo:
      from_secret: tx_docker_repo
    tx_docker_registry:
      from_secret: tx_docker_registry
# trigger:
#   branch:
#   - master